spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/study_planner?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Aymane2004@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

server.port=8080

app.jwt.secret=MySuperSecretKeyForJwtSigningMustBeAtLeast32CharsLong123
app.jwt.expiration-ms=86400000

app.admin.bootstrap-email=admin@studyplanner.com
app.admin.bootstrap-password=Admin123!